field_group.field_group_formatter_plugin.background_color:
  type: field_group.field_group_formatter_plugin.base
  label: 'Mapping for the background color formatter settings'
  mapping:
    color:
      type: string
      label: 'Color field to be used.'
    hide_if_missing:
      type: boolean
      label: 'Whether to hide the field group when the image is missing.'
